# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/puzzle.xdc

# IP: ip/clk_25m/clk_25m.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_25m || ORIG_REF_NAME==clk_25m} -quiet] -quiet
