# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/clk_25m/clk_25m.xci
# IP: The module: 'clk_25m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/clk_25m/clk_25m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/clk_25m/clk_25m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/clk_25m/clk_25m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/clk_25m/clk_25m.xci
# IP: The module: 'clk_25m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/clk_25m/clk_25m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/clk_25m/clk_25m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/clk_25m/clk_25m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
