# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/img_mem/img_mem.xci
# IP: The module: 'img_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/img_mem/img_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/img_mem/img_mem.xci
# IP: The module: 'img_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Arv/puzzle/puzzle.srcs/sources_1/ip/img_mem/img_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
