# VGA related
set_property IOSTANDARD LVCMOS33 [get_ports {O_blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports O_hs]
set_property IOSTANDARD LVCMOS33 [get_ports O_vs]
set_property PACKAGE_PIN H20 [get_ports {O_blue[0]}]
set_property PACKAGE_PIN G20 [get_ports {O_blue[1]}]
set_property PACKAGE_PIN K21 [get_ports {O_blue[2]}]
set_property PACKAGE_PIN K22 [get_ports {O_blue[3]}]
set_property PACKAGE_PIN H17 [get_ports {O_green[0]}]
set_property PACKAGE_PIN H18 [get_ports {O_green[1]}]
set_property PACKAGE_PIN J22 [get_ports {O_green[2]}]
set_property PACKAGE_PIN H22 [get_ports {O_green[3]}]
set_property PACKAGE_PIN G17 [get_ports {O_red[0]}]
set_property PACKAGE_PIN G18 [get_ports {O_red[1]}]
set_property PACKAGE_PIN J15 [get_ports {O_red[2]}]
set_property PACKAGE_PIN H15 [get_ports {O_red[3]}]
set_property PACKAGE_PIN M21 [get_ports O_hs]
set_property PACKAGE_PIN L21 [get_ports O_vs]

# clock and reset
set_property IOSTANDARD LVCMOS33 [get_ports I_clk_100M]
set_property IOSTANDARD LVCMOS33 [get_ports I_rst_n]
set_property PACKAGE_PIN Y18 [get_ports I_clk_100M]
set_property PACKAGE_PIN Y9 [get_ports I_rst_n]

# series port
set_property IOSTANDARD LVCMOS33 [get_ports I_uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports O_uart_tx]
set_property PACKAGE_PIN Y19 [get_ports I_uart_rx]
set_property PACKAGE_PIN V18 [get_ports O_uart_tx]

# LED of status "transimitting"
set_property IOSTANDARD LVCMOS33 [get_ports O_transmitting]
set_property PACKAGE_PIN A21 [get_ports O_transmitting]

# Switches controlling the permutation of puzzle
set_property IOSTANDARD LVCMOS33 [get_ports {I_num[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {I_num[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {I_num[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {I_num[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {I_num[4]}]
set_property PACKAGE_PIN W9 [get_ports {I_num[0]}]
set_property PACKAGE_PIN Y7 [get_ports {I_num[1]}]
set_property PACKAGE_PIN Y8 [get_ports {I_num[2]}]
set_property PACKAGE_PIN AB8 [get_ports {I_num[3]}]
set_property PACKAGE_PIN AA8 [get_ports {I_num[4]}]

# Switch controlling the display of blackhole
set_property IOSTANDARD LVCMOS33 [get_ports I_black_EN]
set_property PACKAGE_PIN V8 [get_ports I_black_EN]

# Up, down, left and right button and set button
set_property IOSTANDARD LVCMOS33 [get_ports I_btn_set]
set_property IOSTANDARD LVCMOS33 [get_ports I_btn_up]
set_property IOSTANDARD LVCMOS33 [get_ports I_btn_down]
set_property IOSTANDARD LVCMOS33 [get_ports I_btn_left]
set_property IOSTANDARD LVCMOS33 [get_ports I_btn_right]
set_property PACKAGE_PIN P4 [get_ports I_btn_set]
set_property PACKAGE_PIN P5 [get_ports I_btn_up]
set_property PACKAGE_PIN P2 [get_ports I_btn_down]
set_property PACKAGE_PIN R1 [get_ports I_btn_right]
set_property PACKAGE_PIN P1 [get_ports I_btn_left]

# # Button of random function
# set_property IOSTANDARD LVCMOS33 [get_ports I_btn_rand]
# set_property PACKAGE_PIN S6 [get_ports I_btn_rand]

# LED of status "completed"
set_property IOSTANDARD LVCMOS33 [get_ports O_completed]
set_property PACKAGE_PIN E22 [get_ports O_completed]

# Switch concerning random
set_property IOSTANDARD LVCMOS33 [get_ports I_rand_move_EN]
set_property PACKAGE_PIN W4 [get_ports I_rand_move_EN]
set_property IOSTANDARD LVCMOS33 [get_ports I_rand_set_EN]
set_property PACKAGE_PIN R4 [get_ports I_rand_set_EN]

# Switch of hard mode
set_property IOSTANDARD LVCMOS33 [get_ports I_hard_mode]
set_property PACKAGE_PIN T4 [get_ports I_hard_mode]

# counter & 7-seg tube by ljy
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg_en_time[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg_en_time[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg_en_time[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg_en_time[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg_en_step[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg_en_step[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg_en_step[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_seg_en_step[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_num[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_num[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_num[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_num[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_num[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_num[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_num[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_num[7]}]
set_property PACKAGE_PIN A18 [get_ports {O_seg_en_step[3]}]
set_property PACKAGE_PIN A20 [get_ports {O_seg_en_step[2]}]
set_property PACKAGE_PIN B20 [get_ports {O_seg_en_step[1]}]
set_property PACKAGE_PIN E18 [get_ports {O_seg_en_step[0]}]
set_property PACKAGE_PIN F18 [get_ports {O_seg_en_time[3]}]
set_property PACKAGE_PIN D19 [get_ports {O_seg_en_time[2]}]
set_property PACKAGE_PIN E19 [get_ports {O_seg_en_time[1]}]
set_property PACKAGE_PIN C19 [get_ports {O_seg_en_time[0]}]
set_property PACKAGE_PIN E13 [get_ports {O_num[7]}]
set_property PACKAGE_PIN C15 [get_ports {O_num[6]}]
set_property PACKAGE_PIN C14 [get_ports {O_num[5]}]
set_property PACKAGE_PIN E17 [get_ports {O_num[4]}]
set_property PACKAGE_PIN F16 [get_ports {O_num[3]}]
set_property PACKAGE_PIN F14 [get_ports {O_num[2]}]
set_property PACKAGE_PIN F13 [get_ports {O_num[1]}]
set_property PACKAGE_PIN F15 [get_ports {O_num[0]}]

# flowing light by myc
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_led[15]}]
set_property PACKAGE_PIN K17 [get_ports {O_led[0]}]
set_property PACKAGE_PIN L13 [get_ports {O_led[1]}]
set_property PACKAGE_PIN M13 [get_ports {O_led[2]}]
set_property PACKAGE_PIN K14 [get_ports {O_led[3]}]
set_property PACKAGE_PIN K13 [get_ports {O_led[4]}]
set_property PACKAGE_PIN M20 [get_ports {O_led[5]}]
set_property PACKAGE_PIN N20 [get_ports {O_led[6]}]
set_property PACKAGE_PIN N19 [get_ports {O_led[7]}]
set_property PACKAGE_PIN M17 [get_ports {O_led[8]}]
set_property PACKAGE_PIN M16 [get_ports {O_led[9]}]
set_property PACKAGE_PIN M15 [get_ports {O_led[10]}]
set_property PACKAGE_PIN K16 [get_ports {O_led[11]}]
set_property PACKAGE_PIN L16 [get_ports {O_led[12]}]
set_property PACKAGE_PIN L15 [get_ports {O_led[13]}]
set_property PACKAGE_PIN L14 [get_ports {O_led[14]}]
set_property PACKAGE_PIN J17 [get_ports {O_led[15]}]


# music by myc
set_property IOSTANDARD LVCMOS33 [get_ports {O_music}]
set_property PACKAGE_PIN A19 [get_ports {O_music}]
set_property IOSTANDARD LVCMOS33 [get_ports {I_music_on}]
set_property PACKAGE_PIN V9 [get_ports {I_music_on}]

